robot_description_param: "/robot_description" 
joint_states_topic:  "/fake_joint_states"
base_frame: "iiwa_link_0"
ee_frame: "iiwa_link_7"
frequency: 10.0
#sensors: [0, 3, 3, 3, 3, 3, 3, 3] #-1: None; 0: FTsensor; 1: Force_x; 4:Torque_x, ...
sensors: [-1, 6, 6, 6, 6, 6, 6, 6] #-1: None; 0: FTsensor; 1: Force_x; 4:Torque_x, ...
sensor_noise: 0.0
pf:
  num_parts: 10000
  search_alpha: 0.01 #aggressiveness of search
  perc_new: 0.9999 # (1-p) percentage of new particles
  #std_devs: [0.01, 0.05, 05.0, 500] #Transition,  pos, Force, K
  std_devs: [0.001, 0.005, 01.0, 5] #Transition,  pos, Force, K
  #std_devs: [0.00, 0.001, 0.10, 1] #Transition,  pos, Force, K
  ranges:
    n: [0, 7]
    F: [0, 150]
    K: [50, 5000]